# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: de # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/
remote_theme: sscit/jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://sissibardesign.sscit.de
baseurl: 
title: SissiBar Design
description: ""
keywords: 'sissibar, design, kunst, blog'
author:
  name: Barbara Schlichthärle
  job_title:
  location: Bayern, Deutschland
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: 
    - name: instagram
      url: https://www.instagram.com/sissibar.design
    - name: linkedin
      url:
    - name: stackoverflow
      url:
    - name: twitter
      url: https://twitter.com/SissiFrau
    - name: vk
      url:
home:
  section1: <h1>SissiBar Design</h1>
  section2: <h2>Lettering und Watercolor für die Schule und Zuhause.</h2>
  section3: 
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: 

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_tag_manager: # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
  imprint: /imprint/
  lp: /lp/
